# Generated by Django 4.2.4 on 2023-10-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historycontent',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
