# Generated by Django 4.2.4 on 2023-10-15 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_historyitem_delete_historycontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
