# Generated by Django 4.2.1 on 2023-08-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character', '0003_alter_character_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='art_forms',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='art_preference',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
