# Generated by Django 4.2.1 on 2023-08-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character', '0004_alter_character_art_forms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='art_forms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='art_preference',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
